### PR TITLE
Feat/search settings

### PR DESCRIPTION
**Pull request by ShahAnuj2610**

### CODE REVIEW

**Comment by jyash97** [comment]
@ShahAnuj2610 this is also having the rules changes in it

**Comment by ShahAnuj2610** [comment]
> @ShahAnuj2610 this is also having the rules changes in it

you can back merge `feat/rules` onto `feat/search-settings`

**Comment by ShahAnuj2610** [comment]
@jyash97 can you back merge `arc` into `feat/search-settings`?

**Comment by jyash97** [comment]
Sure thing.

**Pull request merged**
